from selenium.webdriver.common.by import By


currency_convertor_panel = (By.CSS_SELECTOR, '.b-currency-converter')
currency_convertor_panel_text = (By.CSS_SELECTOR, 'p[class="title"]')
to_sell_button = (By.CSS_SELECTOR, '[for="sale"]')
buy_button = (By.CSS_SELECTOR, '[for="buy"]')
amount_input_field = (By.ID, 'amount-in')
type_of_input_currency = (By.ID, 'currency-in')
currency_in_eur = (By.CSS_SELECTOR, '#currency-in [value="eur"]')
currency_in_usd = (By.CSS_SELECTOR, '#currency-in [value="usd"]')
currency_in_rub = (By.CSS_SELECTOR, '#currency-in [value="rub"]')
currency_in_byn = (By.CSS_SELECTOR, '#currency-in [value="byn"]')
type_currency_out = (By.ID, 'currency-out')
money_logo = (By.CSS_SELECTOR, '.result.to-be-removed span')
nbrb_course = (By.XPATH, '//p[@class="title to-be-removed"]/b[2]')
exchange_rate_calculation_nbrb = (By.XPATH, '//p[@class="title to-be-removed"]/b[1]')
exchange_rate_nbrb_text = (By.CSS_SELECTOR, '.title.to-be-removed')
the_best_exchange_rate_in_the_converter = (By.CSS_SELECTOR, '.bank.to-be-removed i p')
the_best_exchange_rate = (By.CSS_SELECTOR, '.bank.to-be-removed i p b')
estimated_mount = (By.CSS_SELECTOR, '.js-cur-result')
the_best_exchange_rates_line = (By.CSS_SELECTOR, '.b-currency-main__top h1')
information_about_updating_exchange_rate = (By.CLASS_NAME, 'updated')
date = (By.CLASS_NAME, 'th-first')
the_bank_buys = (By.XPATH, '//table[@class="b-currency-table"]/thead/tr/th[2]')
the_bank_sells = (By.XPATH, '//table[@class="b-currency-table"]/thead/tr/th[3]')
nbrb_exchange_rate_text = (By.XPATH, '//table[@class="b-currency-table"]/thead/tr/th[4]')
exchange_rate_fluctuations = (By.CSS_SELECTOR, '.th-last')
currency_information_panel = (By.CSS_SELECTOR, '.tr-main')
information_panel_attribute = (By.XPATH, '//table[@class="b-currency-table__best"]/tbody/tr/td/p/b')
exchange_rate_in_banks = (By.XPATH, '//p[@class="bank"]/a')
banks = (By.XPATH, '//td[@class="bank"]')
maps = (By.CLASS_NAME, 'b-currency-map-i')
button_fluctuations_in_the_best_rates = (By.CSS_SELECTOR, '.b-currency-chart__toggle li a')
